//
//  TypeEffectiveness.swift
//  PGoLib
//
//  Created by 임채윤 on 8/17/24.
//

import Foundation

struct TypeEffectiveness {
    private let effectiveness: [PokemonTypes: [PokemonTypes: Double]] = [
        .bug: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .electric: 1,
            .fairy   : 1,
            .ghost   : 1,
            .ice     : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .steel   : 1,
            .water   : 1,
            .fire    : 1.6,
            .flying  : 1.6,
            .rock    : 1.6,
            .fighting: 0.63,
            .grass   : 0.63,
            .ground  : 0.63,
        ],
        .dark: [
            .dragon  : 1,
            .electric: 1,
            .fire    : 1,
            .flying  : 1,
            .grass   : 1,
            .ground  : 1,
            .ice     : 1,
            .normal  : 1,
            .poison  : 1,
            .rock    : 1,
            .steel   : 1,
            .water   : 1,
            .bug     : 1.6,
            .fairy   : 1.6,
            .fighting: 1.6,
            .psychic : 0.39,
            .dark    : 0.63,
            .ghost   : 0.63,
        ],
        .dragon: [
            .bug     : 1,
            .dark    : 1,
            .fighting: 1,
            .flying  : 1,
            .ghost   : 1,
            .ground  : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .rock    : 1,
            .steel   : 1,
            .dragon  : 1.6,
            .fairy   : 1.6,
            .ice     : 1.6,
            .electric: 0.63,
            .fire    : 0.63,
            .grass   : 0.63,
            .water   : 0.63,
        ],
        .electric: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .fairy   : 1,
            .fighting: 1,
            .fire    : 1,
            .ghost   : 1,
            .grass   : 1,
            .ice     : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .rock    : 1,
            .water   : 1,
            .ground  : 1.6,
            .electric: 0.63,
            .flying  : 0.63,
            .steel   : 0.63,
        ],
        .fairy: [
            .electric: 1,
            .fairy   : 1,
            .fire    : 1,
            .flying  : 1,
            .ghost   : 1,
            .grass   : 1,
            .ground  : 1,
            .ice     : 1,
            .normal  : 1,
            .psychic : 1,
            .rock    : 1,
            .water   : 1,
            .poison  : 1.6,
            .steel   : 1.6,
            .dragon  : 0.39,
            .bug     : 0.63,
            .dark    : 0.63,
            .fighting: 0.63,
        ],
        .fighting: [
            .dragon  : 1,
            .electric: 1,
            .fighting: 1,
            .fire    : 1,
            .ghost   : 1,
            .grass   : 1,
            .ground  : 1,
            .ice     : 1,
            .normal  : 1,
            .poison  : 1,
            .steel   : 1,
            .water   : 1,
            .fairy   : 1.6,
            .flying  : 1.6,
            .psychic : 1.6,
            .bug     : 0.63,
            .dark    : 0.63,
            .rock    : 0.63,
        ],
        .fire: [
            .dark    : 1,
            .dragon  : 1,
            .electric: 1,
            .fighting: 1,
            .flying  : 1,
            .ghost   : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .ground  : 1.6,
            .rock    : 1.6,
            .water   : 1.6,
            .bug     : 0.63,
            .fairy   : 0.63,
            .fire    : 0.63,
            .grass   : 0.63,
            .ice     : 0.63,
            .steel   : 0.63,
        ],
        .flying: [
            .dark    : 1,
            .dragon  : 1,
            .fairy   : 1,
            .fire    : 1,
            .flying  : 1,
            .ghost   : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .steel   : 1,
            .water   : 1,
            .electric: 1.6,
            .ice     : 1.6,
            .rock    : 1.6,
            .ground  : 0.39,
            .bug     : 0.63,
            .fighting: 0.63,
            .grass   : 0.63,
        ],
        .ghost: [
            .dragon  : 1,
            .electric: 1,
            .fairy   : 1,
            .fire    : 1,
            .flying  : 1,
            .grass   : 1,
            .ground  : 1,
            .ice     : 1,
            .psychic : 1,
            .rock    : 1,
            .steel   : 1,
            .water   : 1,
            .dark    : 1.6,
            .ghost   : 1.6,
            .fighting: 0.39,
            .normal  : 0.39,
            .bug     : 0.63,
            .poison  : 0.63,
        ],
        .grass: [
            .dark    : 1,
            .dragon  : 1,
            .fairy   : 1,
            .fighting: 1,
            .ghost   : 1,
            .normal  : 1,
            .psychic : 1,
            .rock    : 1,
            .steel   : 1,
            .bug     : 1.6,
            .fire    : 1.6,
            .flying  : 1.6,
            .ice     : 1.6,
            .poison  : 1.6,
            .electric: 0.63,
            .grass   : 0.63,
            .ground  : 0.63,
            .water   : 0.63,
        ],
        .ground: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .fairy   : 1,
            .fighting: 1,
            .fire    : 1,
            .flying  : 1,
            .ghost   : 1,
            .ground  : 1,
            .normal  : 1,
            .psychic : 1,
            .steel   : 1,
            .grass   : 1.6,
            .ice     : 1.6,
            .water   : 1.6,
            .electric: 0.39,
            .poison  : 0.63,
            .rock    : 0.63,
        ],
        .ice: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .electric: 1,
            .fairy   : 1,
            .flying  : 1,
            .ghost   : 1,
            .grass   : 1,
            .ground  : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .water   : 1,
            .fighting: 1.6,
            .fire    : 1.6,
            .rock    : 1.6,
            .steel   : 1.6,
            .ice     : 0.63,
        ],
        .normal: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .electric: 1,
            .fairy   : 1,
            .fire    : 1,
            .flying  : 1,
            .grass   : 1,
            .ground  : 1,
            .ice     : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .rock    : 1,
            .steel   : 1,
            .water   : 1,
            .fighting: 1.6,
            .ghost   : 0.39,
        ],
        .poison: [
            .dark    : 1,
            .dragon  : 1,
            .electric: 1,
            .fire    : 1,
            .flying  : 1,
            .ghost   : 1,
            .ice     : 1,
            .normal  : 1,
            .rock    : 1,
            .steel   : 1,
            .water   : 1,
            .ground  : 1.6,
            .psychic : 1.6,
            .bug     : 0.63,
            .fairy   : 0.63,
            .fighting: 0.63,
            .grass   : 0.63,
            .poison  : 0.63,
        ],
        .psychic: [
            .dragon  : 1,
            .electric: 1,
            .fairy   : 1,
            .fire    : 1,
            .flying  : 1,
            .grass   : 1,
            .ground  : 1,
            .ice     : 1,
            .normal  : 1,
            .poison  : 1,
            .rock    : 1,
            .steel   : 1,
            .water   : 1,
            .bug     : 1.6,
            .dark    : 1.6,
            .ghost   : 1.6,
            .fighting: 0.63,
            .psychic : 0.63,
        ],
        .rock: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .electric: 1,
            .fairy   : 1,
            .ghost   : 1,
            .ice     : 1,
            .psychic : 1,
            .rock    : 1,
            .fighting: 1.6,
            .grass   : 1.6,
            .ground  : 1.6,
            .steel   : 1.6,
            .water   : 1.6,
            .fire    : 0.63,
            .flying  : 0.63,
            .normal  : 0.63,
            .poison  : 0.63,
        ],
        .steel: [
            .dark    : 1,
            .electric: 1,
            .ghost   : 1,
            .water   : 1,
            .fighting: 1.6,
            .fire    : 1.6,
            .ground  : 1.6,
            .poison  : 0.39,
            .bug     : 0.63,
            .dragon  : 0.63,
            .fairy   : 0.63,
            .flying  : 0.63,
            .grass   : 0.63,
            .ice     : 0.63,
            .normal  : 0.63,
            .psychic : 0.63,
            .rock    : 0.63,
            .steel   : 0.63,
        ],
        .water: [
            .bug     : 1,
            .dark    : 1,
            .dragon  : 1,
            .fairy   : 1,
            .fighting: 1,
            .flying  : 1,
            .ghost   : 1,
            .ground  : 1,
            .normal  : 1,
            .poison  : 1,
            .psychic : 1,
            .rock    : 1,
            .electric: 1.6,
            .grass   : 1.6,
            .fire    : 0.63,
            .ice     : 0.63,
            .steel   : 0.63,
            .water   : 0.63,
        ],
    ]
    
    func calculate(_ selectedTypes: [PokemonTypes]) -> Effectiveness? {
        guard !selectedTypes.isEmpty else { return nil }
        
        var mergedEffectiveness = [PokemonTypes: Double]()
        
        selectedTypes.forEach { selectedType in
            if let effectiveness = effectiveness[selectedType] {
                effectiveness.forEach { (type, coefficient) in
                    mergedEffectiveness[type, default: 1.0] *= coefficient
                }
            }
        }
        
        let sortedEffectiveness = mergedEffectiveness.sorted { $0.key.rawValue < $1.key.rawValue }
                                                     .map { ($0, $1.rounded(toPlaces: 2)) }
        
        return Effectiveness(effectiveness: sortedEffectiveness)
    }
}
